// <auto-generated />
using System;
using Async_Inn_app.data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Async_Inn_app.Migrations
{
    [DbContext(typeof(AsyncInnDbContext))]
    [Migration("20220418085156_Update-Migration1")]
    partial class UpdateMigration1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.16")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Async_Inn_app.models.Amenities", b =>
                {
                    b.Property<int>("amenitiesId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("amenitiesId");

                    b.ToTable("Amenities");
                });

            modelBuilder.Entity("Async_Inn_app.models.Employees", b =>
                {
                    b.Property<int>("empId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("HotelBrancheshotelId")
                        .HasColumnType("int");

                    b.Property<int>("hotelId")
                        .HasColumnType("int");

                    b.Property<decimal>("salary")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("workTitle")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("empId");

                    b.HasIndex("HotelBrancheshotelId");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("Async_Inn_app.models.HotelBranches", b =>
                {
                    b.Property<int>("hotelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("city")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("phoneNum")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("roomsNum")
                        .HasColumnType("int");

                    b.Property<string>("state")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("hotelId");

                    b.ToTable("HotelBranches");
                });

            modelBuilder.Entity("Async_Inn_app.models.Rooms", b =>
                {
                    b.Property<int>("hotelIdRoomId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("HotelBrancheshotelId")
                        .HasColumnType("int");

                    b.Property<int>("hotelId")
                        .HasColumnType("int");

                    b.Property<string>("nickName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("roomId")
                        .HasColumnType("int");

                    b.Property<int>("space")
                        .HasColumnType("int");

                    b.Property<int>("visitorId")
                        .HasColumnType("int");

                    b.HasKey("hotelIdRoomId");

                    b.HasIndex("HotelBrancheshotelId");

                    b.ToTable("Rooms");
                });

            modelBuilder.Entity("Async_Inn_app.models.Employees", b =>
                {
                    b.HasOne("Async_Inn_app.models.HotelBranches", "HotelBranches")
                        .WithMany()
                        .HasForeignKey("HotelBrancheshotelId");

                    b.Navigation("HotelBranches");
                });

            modelBuilder.Entity("Async_Inn_app.models.Rooms", b =>
                {
                    b.HasOne("Async_Inn_app.models.HotelBranches", "HotelBranches")
                        .WithMany()
                        .HasForeignKey("HotelBrancheshotelId");

                    b.Navigation("HotelBranches");
                });
#pragma warning restore 612, 618
        }
    }
}
